spring:
  datasource:
    url: jdbc:sqlserver://10.10.114.242;databaseName=qiyewan_management;useUnicode=true;characterEncoding=GBK
    username: sa
    password: qiyewan2016
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialize: false
  jpa:
    database: sql_server
    database-platform: SQL_SERVER
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect